# Generated by Django 2.1.5 on 2019-03-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0004_auto_20190309_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='parent_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hero_upgrade_system.Ability'),
        ),
    ]
