# Generated by Django 2.1.5 on 2019-03-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0005_auto_20190310_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='parent_ability',
            new_name='parent',
        ),
    ]
