# Generated by Django 2.1.5 on 2019-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0006_auto_20190310_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
