# Generated by Django 2.1.5 on 2019-03-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0007_auto_20190310_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='ability_function',
            new_name='function',
        ),
    ]
