# Generated by Django 2.1.5 on 2019-03-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0009_auto_20190310_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='module',
            field=models.CharField(choices=[('hero_upgrade_system.models.occupations.warrior', 'hero_upgrade_system.models.occupations.warrior'), ('hero_upgrade_system.models.occupations.mage', 'hero_upgrade_system.models.occupations.mage'), ('hero_upgrade_system.models.occupations.thief', 'hero_upgrade_system.models.occupations.thief')], max_length=100),
        ),
    ]
