# Generated by Django 2.1.5 on 2019-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0013_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='description',
            field=models.TextField(default='Warrior is ...'),
            preserve_default=False,
        ),
    ]
