# Generated by Django 2.1.5 on 2019-03-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_auto_20190313_1948'),
        ('hero_upgrade_system', '0014_occupation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroability',
            name='hero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hero.Hero'),
            preserve_default=False,
        ),
    ]
