# Generated by Django 2.1.5 on 2019-03-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0015_heroability_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='description',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='points',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
