# Generated by Django 2.1.7 on 2019-03-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0016_auto_20190318_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='hero',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
