# Generated by Django 2.1.7 on 2019-03-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0017_auto_20190329_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='heroability',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='heroability',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='heroability',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
        migrations.DeleteModel(
            name='HeroAbility',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
