# Generated by Django 2.1.7 on 2019-04-29 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[(1, 'easy'), (1.5, 'medium'), (2, 'hard')], max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifical.Location')),
            ],
        ),
        migrations.CreateModel(
            name='MobClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_statistic', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mob',
            name='mob_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifical.MobClass'),
        ),
    ]
