# Generated by Django 2.1.7 on 2019-04-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_upgrade', '0003_auto_20190405_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MobClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('physic', 'physic'), ('magic', 'magic'), ('agile', 'agile'), ('tanky', 'tanky')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MobStatistics',
            fields=[
                ('statistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general_upgrade.Statistic')),
                ('level', models.PositiveIntegerField(default=1)),
            ],
            bases=('general_upgrade.statistic',),
        ),
        migrations.AddField(
            model_name='mob',
            name='mob_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifical.MobClass'),
        ),
    ]
