# Generated by Django 2.1.7 on 2019-04-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artifical.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobstatistics',
            name='mob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artifical.Mob'),
            preserve_default=False,
        ),
    ]
