# Generated by Django 2.1.7 on 2019-04-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_auto_20190405_1624'),
        ('general_upgrade', '0003_auto_20190405_1624'),
        ('artifical', '0002_auto_20190405_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatistics',
            fields=[
                ('statistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general_upgrade.Statistic')),
            ],
            bases=('general_upgrade.statistic',),
        ),
        migrations.CreateModel(
            name='HeroItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artifical.Item')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Hero')),
            ],
            bases=('artifical.item',),
        ),
        migrations.AddField(
            model_name='itemstatistics',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifical.Item'),
        ),
    ]
