# Generated by Django 2.1.7 on 2019-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifical', '0003_auto_20190405_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobclass',
            name='main_statistic',
            field=models.CharField(choices=[('strength', 'strength'), ('agility', 'agility'), ('intelligence', 'intelligence'), ('health', 'health')], default='strength', max_length=50),
            preserve_default=False,
        ),
    ]
