# Generated by Django 2.1.7 on 2019-04-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_upgrade', '0003_auto_20190405_1624'),
        ('artifical', '0005_auto_20190406_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FightingMobStatistics',
            new_name='FightingMobStatistic',
        ),
    ]
