# Generated by Django 2.1.7 on 2019-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifical', '0007_auto_20190406_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightingmob',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='fightingmobstatistic',
            name='mob',
        ),

        migrations.AlterField(
            model_name='mob',
            name='difficulty',
            field=models.CharField(choices=[(1, 'easy'), (1.5, 'medium'), (2, 'hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mobclass',
            name='main_statistic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='FightingMob',
        ),
        migrations.DeleteModel(
            name='FightingMobStatistic',
        ),
    ]
