# Generated by Django 2.1.7 on 2019-04-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifical', '0008_auto_20190408_1907'),
        ('general_upgrade', '0003_auto_20190405_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightingMob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifical.Mob')),
            ],
        ),
        migrations.CreateModel(
            name='FightingMobStatistic',
            fields=[
                ('statistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general_upgrade.Statistic')),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combat_system.FightingMob')),
            ],
            bases=('general_upgrade.statistic',),
        ),
    ]
