# Generated by Django 2.1.5 on 2019-03-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='user',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='hero',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
