# Generated by Django 2.1.7 on 2019-04-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_upgrade', '0001_initial'),
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herostatistic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='herostatistic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='herostatistic',
            name='points',
        ),
        migrations.AddField(
            model_name='herostatistic',
            name='statistic_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general_upgrade.Statistic'),
            preserve_default=False,
        ),
    ]
