# Generated by Django 2.1.7 on 2019-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20190404_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostatistic',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
