# Generated by Django 2.1.7 on 2019-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_herostatistic_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herostatistic',
            name='experience',
        ),
        migrations.AddField(
            model_name='hero',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
