# Generated by Django 2.1.5 on 2019-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_hero_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(choices=[('strength', 'strength'), ('agility', 'agility'), ('intelligence', 'intelligence')], max_length=35),
        ),
    ]
