# Generated by Django 2.1.5 on 2019-03-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero_upgrade_system', '0004_auto_20190309_1915'),
        ('hero', '0004_auto_20190309_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='occupation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hero_upgrade_system.Occupation'),
            preserve_default=False,
        ),
    ]
