# Generated by Django 2.1.5 on 2019-03-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_hero_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='hero',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
