# Generated by Django 2.1.5 on 2019-03-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_auto_20190313_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='ability_points',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hero',
            name='statistic_points',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
