# Generated by Django 2.1.7 on 2019-03-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('warrior', 'Warrior'), ('thief', 'Thief'), ('mage', 'Mage')], max_length=35)),
                ('module', models.CharField(choices=[('hero_upgrade_system.models.occupations.warrior', 'hero_upgrade_system.models.occupations.warrior'), ('hero_upgrade_system.models.occupations.mage', 'hero_upgrade_system.models.occupations.mage'), ('hero_upgrade_system.models.occupations.thief', 'hero_upgrade_system.models.occupations.thief')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Occupation'),
        ),
    ]
